default:
  tags:
    - linux/amd64

image: registry.qiuzhi.tech/library/python:3.9

before_script:
  - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

test:
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
