site_name: AIRBOT Play 产品文档
site_url: https://discover-robotics.github.io/docs
site_dir: public
theme:
  language: en 
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Lato
    code: Space Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
plugins:
  - search
  - enumerate-headings:
      increment_across_pages: false
      exclude_h1: true
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Chinese
      link: /zh/ 
      lang: zh
  homepage: https://airbots.online
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
nav:
  - Welcome: README.md
  - Software SDK:
    - C++ Interface: "https://discover-robotics.github.io/docs/cpp/"
    - ROS1 Interface: sdk/ROS1.md