site_name: AIRBOT 产品文档
site_url: http://127.0.0.1:8000/docs
site_dir: public
theme:
  language: en 
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Lato
    code: Space Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
plugins:
  - search
  - enumerate-headings:
      increment_across_pages: false
      exclude_h1: true
  - redirects:
      redirect_maps:
        'index.md': 'AIRBOT-Play/manual/spec.md'

extra:
  version:
    provider: mike
    default: latest
    alias: true
  homepage: https://airbots.online
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - AIRBOT Play:
    - 产品手册: 
      # - 产品介绍: AIRBOT-Play/manual/introduction.md
      - 技术参数: AIRBOT-Play/manual/spec.md
      - 包装清单: AIRBOT-Play/manual/package_contents.md
      - 开箱点亮: AIRBOT-Play/manual/installation.md
      - 末端执行器更换: AIRBOT-Play/manual/end_effectors.md
      - FAQ: AIRBOT-Play/manual/faq.md
    - 使用教程:
      - 软件环境配置: AIRBOT-Play/tutorials/env.md
      - 软件工具使用说明: AIRBOT-Play/tutorials/tools.md
      - 机械臂零点标定: AIRBOT-Play/tutorials/set_zero.md
      - 机械臂状态说明: AIRBOT-Play/tutorials/states.md
      - 机械臂固件升级: AIRBOT-Play/tutorials/upgrade.md
      - 教程：数据采集: AIRBOT-Play/tutorials/aloha.md
    - SDK 文档:
      - Python : python/
      - ROS 1 : AIRBOT-Play/sdk/ros1.md
      - C++: cpp/

  # - Product Manual:
  #   - AIRBOT Play: manual/airbot-play/index.md
  #   - AIRBOT Play Pro: manual/airbot-play-pro/index.md
  # - Software SDK: 
  #   - sdk/index.md
  #   - C++ Interface: cpp/
  #   - ROS1 Interface: sdk/ROS1.md
  #   - Python Interface: python/
  # - Applications:
  #   - ALOHA: sdk/aloha.md
  # - Firmware Upgrade Guide:
  #   - AIRBOT Play: upgrade/airbot-play.md


