install(
  TARGETS ${PROJECT_NAME} nlohmann_json httplib kdl_parser
  EXPORT ${PROJECT_NAME}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})

install(
  DIRECTORY src/ ${PROJECT_NAME}
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
  FILES_MATCHING
  PATTERN "*.h")

install(
  DIRECTORY src/ ${PROJECT_NAME}
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
  FILES_MATCHING
  PATTERN "*.hpp")

install(FILES ${VERSION_HEADER} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/airbot)

install(
  DIRECTORY models/
  DESTINATION ${CMAKE_INSTALL_PREFIX}/share/${PROJECT_NAME}
  FILES_MATCHING
  PATTERN "*")

install(
  EXPORT ${PROJECT_NAME}
  FILE ${PROJECT_NAME}Targets.cmake
  NAMESPACE ${PROJECT_NAME}::
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME})

include(CMakePackageConfigHelpers)
write_basic_package_version_file(
  ${PROJECT_NAME}Version.cmake
  VERSION ${PROJECT_VERSION}
  COMPATIBILITY AnyNewerVersion)

install(FILES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Version.cmake"
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME})

configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/Config.cmake.in"
               "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake" @ONLY)

# Install the Config.cmake file
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME})

# Install udev
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/sys/99-airbot.rules
        DESTINATION /etc/udev/rules.d)
install(PROGRAMS ${CMAKE_CURRENT_SOURCE_DIR}/sys/configure-can.sh
        DESTINATION ${CMAKE_INSTALL_BINDIR})

set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
