name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: pip install thirdparty/mkdocs-enumerate-headings-plugin
      - run: mkdocs gh-deploy --force
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            working-directory: 'thirdparty/arm-control'
            # enable-latex: true
      - run: mkdir -p public && cp -r thirdparty/arm-control/doc/html public/cpp
      - run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: cd public && git init && git add . && git commit -m "Deploy" && git push --force