name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: pip install thirdparty/mkdocs-enumerate-headings-plugin
      - run: mkdocs gh-deploy --force
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            working-directory: 'thirdparty/arm-control'
            # enable-latex: true
      - run: mkdir -p public && cp -r thirdparty/arm-control/doc/html public/cpp
        # python interface docs generate
      - run: sudo apt install -y ./.github/workflows/airbot_play_2.7.1_amd64.deb
      - run: sudo apt install -y can-utils cmake libeigen3-dev libcppunit-dev liburdfdom-dev libtinyxml2-dev libkdl-parser-dev libboost-serialization-dev libboost-thread-dev build-essential libncurses5-dev libspdlog-dev
      - run: cd thirdparty/python-interface-docs && pip install -r requirements.txt && cd ..
      - run: cd thirdparty/sdk && git submodule update --init --recursive && cd python
      - run: python -m pybind11_mkdoc -o src/doc.hpp -I/usr/include/eigen3 -std=c++17 /usr/include/airbot/command/command_base.hpp /usr/include/airbot/modules/motors/motor_driver.hpp
      - run: pip install -e . && cd ../..
      - run: cd python-interface-docs && make html && cd ../..
      - run: mkdir public/python && cp -r thirdparty/python-interface-docs/build/html public/python
      - run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: |
          cd public
          git init
          git add .
          git checkout -b gh-pages
          git commit -m "Deploy"
          git remote add origin https://${{ secrets.GH_PAT }}@github.com/DISCOVER-Robotics/docs.git
          git push --force --set-upstream origin gh-pages
