name: ci 
on:
  push:
    branches:
      - master 
      - dev
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: pip install thirdparty/mkdocs-enumerate-headings-plugin
      # - run: mkdocs gh-deploy --force
      - run: git fetch origin gh-pages --depth=1
      - run: git config user.name ci-bot
      - run: git config user.email ci-bot@example.com
      - run: mike deploy --push --update-aliases latest
      # copy cpp doc to public
      - run: mkdir -p public && cp -r thirdparty/arm-control/html public/cpp
      # copy python doc to public
      - run: cp -r thirdparty/pythondoc/html public/python
      - run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: |
          cd public
          git init
          touch .nojekyll
          git add .
          git checkout -b gh-pages
          git commit -m "Deploy"
          git remote add origin https://${{ secrets.GH_PAT }}@github.com/DISCOVER-Robotics/docs.git
          git push --force --set-upstream origin gh-pages
