name: ci 
on:
  push:
    branches:
      - master 
      - dev
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: pip install thirdparty/mkdocs-enumerate-headings-plugin
      - run: git fetch origin gh-pages --depth=1
      - run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      # - run: mkdocs gh-deploy --force
      - run: mike deploy --push --update-aliases latest
      # copy cpp doc to public
      - run: git clone -b gh-pages https://${{ secrets.GH_PAT }}@github.com/DISCOVER-Robotics/docs.git pages
      - run: cp -r thirdparty/arm-control/html pages/latest/cpp
      - run: cp -r thirdparty/pythondoc/html pages/latest/python
      - run: git add .
      - run: git commit -m "Deploy"
      - run: git push