name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: pip install thirdparty/mkdocs-enumerate-headings-plugin
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            working-directory: 'thirdparty/arm-control'
            enable-latex: true
      - run: mv submodule/arm-control/doc/html public/cpp
      - run: mkdocs gh-deploy --force